import { Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

const merriweather = Merriweather({ weight:'400',subsets: ["latin"] });

export const metadata = {
  title: "Landing page example",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={merriweather.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
